# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

# FindSpark simplifies the process of using Apache Spark with Python

import findspark
findspark.init()

#import functions/Classes for sparkml

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("SparkSQL").getOrCreate()
mpg_data = spark.read.csv("mpg.csv", header=True, inferSchema=True)
mpg_data.createOrReplaceTempView("mileage")
results = spark.sql("SELECT * FROM mileage WHERE MPG > 40")
results.show()
spark.sql("SELECT distinct Origin FROM mileage").show()
spark.sql("SELECT Year, count(Year) FROM mileage group by Year").show()
spark.sql("SELECT max(MPG) FROM mileage").show()
spark.stop()
